environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug
      
build_script:
  - dir C:\
  - dir C:\msys64
  - dir C:\mingw64
  - SET PATH=C:\mingw64\bin;C:\msys64;%PATH%	
  - bash -c configure
  - bash -c make
  - bash -c "make check"
  - bash -c "make distcheck"
