environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug
      
build_script:
  - dir C:\
  - dir C:\msys64
  - dir C:\mingw-w64
  - SET PATH=C:\mingw-w64\bin;C:\msys64\mingw64\bin;%PATH%	
  - echo "%PATH%"
  - path
  - bash -c "env"
  - bash -c ./configure
  - bash -c make
  - bash -c "make check"
  - bash -c "make distcheck"
