environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug
      
build_script:
  - dir C:\
  - dir C:\msys64
  - dir C:\msys64\usr
  - dir C:\msys64\opt
  - dir C:\msys64\mingw64
  - dir C:\msys64\mingw64\x86_64-w64-mingw32
  - dir C:\msys64\mingw64\x86_64-w64-mingw32\bin
  - dir C:\mingw-w64
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\opt
  - SET PATH=C:\mingw-w64\bin;C:\msys64\mingw64\bin;%PATH%	
  - echo "%PATH%"
  - path
  - bash -c "env"
  - bash -c pwd
  - bash -c ls
  - dir c:\msys64\mingw64\bin
  - mingw-get install autoconf automake gettext libtool
  - bash -c autoreconf -i -f
  - bash -c "./configure"
  - bash -c make
  - bash -c "make check"
  - bash -c "make distcheck"
