environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug
      
build_script:
  - dir C:\
  - SET PATH=C:\MinGW\bin;%PATH%	
  - bash -c configure
  - bash -c make
  - bash -c "make check"
  - bash -c "make distcheck"
