environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug
      
build_script:
  - SET PATH=C:\MinGW\bin;%PATH%	
  - configure
  - make
  - make check
  - make distcheck
